const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

  //admin
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  // login user success
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  // add cart
  ADD_CART_SUCCESS: "ADD_CART_SUCCESS",
  // update cart
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  // change language
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
});

export default actionTypes;
